# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a71b64d73fa0bfa0d83c37eb38449f3fec3687d0ea2ab0dd09c09135fda9710755c81405fbb9538f6777989c67e18643a73cb1f9aed1cf7d157a85d80bba421b

test:
  secret_key_base: 1adc52241011cd15e8e757558e0aa1620b75e7217fddc01ba2906973f935b4ff1005ba49c58194b7f4657b04ade79ca0e0c9fc6ce6831a03ff3a33fef9c00cf5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
